spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lottery?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&useSSL=false
    username: root
    password: lovegfm99
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1 # Redis????? 1.117.84.9
    database: 0 # Redis?????????0?
    port: 6379 # Redis???????
    password:   # Redis?????????????614571
    jedis:
      pool:
        max-active: 8 # ????????????????????
        max-wait: -1ms # ???????????????????????
        max-idle: 8 # ???????????
        min-idle: 0 # ???????????
    timeout: 10000ms # ??????????

mybatis-plus:
  type-enums-package: cn.flik1337.lotteryHelper.common.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

remote:
  baseUrl:
    wechat: https://api.weixin.qq.com

wechat:
  appId: wxc5cf8c53c95a6390
  secret: 9592ccece36e898f43249043735fd1db

qiniu:
  AccessKey: nMED_cospE1W9CYhYBTwP-GI0150Gh8Mhm0vq_Zf
  SecretKey: 0fJs1ntpZygmAkF1gughSU6XXYHJRG0DwEG6_bsv
  bucketName: flik1337-blog
